[default.extend-words]

# CodeMirror module / symbol names
"crosshairCursor" = "crosshairCursor"

[files]
extend-exclude = [
  "dioxus_codemirror/assets/codemirror-vendor",
  "example/assets/licenses.html",
]
